package com.cthnic001.hue;

/**
 * Created by CTHNI_000 on 2014-08-29.
 */
public enum TileType {
    WIRE, INVERTER, TERMINATOR, EXIT, TURN_TABLE, SLIDER, POWER_SOURCE, ISOLATOR, FILTER, GROUND, MOMENTARY_SWITCH, SWITCH, TURNTABLE_SWITCH, VOID
}
